### ISSUE TITLE
Timeout when creating container

### ISSUE THREAD

**Issue by willnx** [willnx/container_shell#26]
A user encountered this problem:
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "container_shell/container_shell.py", line 174, in <module>
  File "container_shell/container_shell.py", line 60, in main
  File "docker/models/containers.py", line 843, in create
  File "docker/api/container.py", line 427, in create_container
  File "docker/api/container.py", line 437, in create_container_from_config
  File "docker/api/client.py", line 289, in _post_json
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 226, in _post
  File "requests/sessions.py", line 581, in post
  File "requests/sessions.py", line 533, in request
  File "requests/sessions.py", line 646, in send
  File "requests/adapters.py", line 529, in send
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
[20029] Failed to execute script container_shell
```

Looks like more of a _docker issue_, because [line 60](https://github.com/willnx/container_shell/blob/master/container_shell/container_shell.py#L60) in `container_shell/container_shell.py` is when I call the Docker daemon to create the container.

**Comment by willnx** [comment]
I found a similar problem for `docker-compose`; it uses the same Python binds as `container_shell` for talking to the Docker daemon: https://github.com/docker/compose/issues/3927
That thread is _full_ of users saying either:
A) They restarted docker and it's now working
-or-
B) They upped the timeout, and it's better/working

(along  with the expected people commenting _"I have this problem too"_ and other common noise)

Looking at the stats for the server, it doesn't look like resource starvation 🤔 Infact, this happened during a _down point_ in utilization.

**Comment by willnx** [comment]
Hmm... the plot thickens 🤔 
```
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/gsm-d8d2d6] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/gsm-6ed37d] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/prasar19-8f9740] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/gsm-504c1e] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/gsm-213619] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/ballaa2-5db69a] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/andrep2-4d1d00] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/gsm-d3edb0] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/gsm-8b9410] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/gsm-78f7a9] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/andrep2-125645] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
May 16 22:35:10 evsappprd001 telegraf[17775]: 2020-05-17T02:35:10Z E! [inputs.docker]: Error in plugin: E! Error gathering container [/gsm-d1e5a9] stats: Error getting docker stats: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
